// Every string the UI shows, in one place, from day one (i18n-ready,
// English only). Screens import from here; they do not carry prose of
// their own. Step 7 adds the glossary (one-line explainers for every
// technical term) next to this file.

function capitalise(s: string): string {
  return s ? s[0].toUpperCase() + s.slice(1) : s
}

export const en = {
  app: {
    title: 'Local LLM Advisor',
    tagline: 'Which AI models fit this computer, and how well they run.',
    advancedOn: 'Advanced',
    version: (v: string) => `version ${v}`,
    daemonUnreachable: 'The advisor is not running on this computer. Start it and reload this page.',
  },
  figure: {
    estimatedLabel: 'estimated',
    measuredLabel: 'measured on this computer',
    estimatedPrefix: '≈',
  },
  // Public data (step 9b): numbers others published about a model — never
  // about this computer. research/EXTERNAL_SOURCES.md P-4 to P-7.
  publicData: {
    label: 'published by others',
    title: 'Public data — how others rated this model',
    cardTitle: 'Public data',
    tests: (what: string, who: string) => `${capitalise(what)} — ${who}.`,
    publishedBy: (publisher: string, date: string) => `${publisher}, ${date}.`,
    readAtSource: 'Read it at the source',
    none: 'No public scores for this size yet. Other people\'s results for a bigger or smaller size of the same model are not shown here: they would say little about this one.',
    caveatBefore: 'These scores are for the original model as its maker published it. What Ollama downloads is a compressed copy (its ',
    caveatAfter: '), which may score a little lower.',
    whatIsIt: 'What is a',
    notScored: 'Reported by the model\'s maker: shown, but not used to rank models, because makers test their own models in different ways.',
    advanced: 'Details',
  },
  // Every wait shows what is happening and that it is still happening: a
  // moving bar and the time so far (Itay, testing on Windows, 2026-09-24).
  working: {
    elapsed: (s: number) => (s < 60 ? `${s} s so far` : `${Math.floor(s / 60)} min ${String(s % 60).padStart(2, '0')} s so far`),
  },
  // The model list, on every screen that needs it (GET /api/catalog/status).
  modelList: {
    missingTitle: 'The list of models has not been fetched yet',
    missingLead:
      'The advisor needs its list of models — their names, sizes and how they are built — before it can recommend one or offer one to test. Fetching it downloads descriptions only, never the models themselves.',
    fetch: 'Get the model list (a few MB of descriptions, no models)',
    refetch: 'Get the list again (a few MB)',
    fetchedOn: (when: string) => `Model list fetched ${when}.`,
    starting: 'Starting to fetch the model list…',
    phaseModels: 'Fetching the list of models from Hugging Face',
    publicBackground: 'Public scores are downloading in the background',
    publicBackgroundLead:
      'Everything else works meanwhile; recommendations pick the scores up by themselves when they arrive.',
    partOf: (done: number, total: number) => `${done} of ${total} done`,
    progressLabel: 'Fetching the model list',
    failed: (message: string) => `The model list could not be fetched: ${message}`,
    stopped: (why: string) => `The fetch stopped early: ${why}. Try again when this computer is online.`,
    publicMissing:
      'Public scores come with the model list: fetching it again also reads the scores other people have published (a few MB, no models).',
    fetchPublic: 'Get public scores now (a few MB, no models)',
  },
  nav: {
    home: 'Home',
    computer: 'Your computer',
    ollama: 'Ollama',
    models: 'Models',
    recommend: 'Recommend',
    benchmarks: 'Benchmarks',
    watch: 'New models',
    settings: 'Settings',
    modelDetail: 'Model',
  },
  screens: {
    home: {
      title: 'Home',
      loading: 'Looking at this computer…',
      failed: (message: string) => `This computer could not be read: ${message}`,
      yourModel: 'Your model',
      modelMeasured: 'answers at',
      nextTitle: 'What to do next',
      next: {
        installTitle: "Ollama isn't running",
        installLead: "Ollama runs the models on this computer; without it, nothing can answer anything.",
        install: (size?: string) => (size ? `Install Ollama (about ${size})` : 'Install Ollama'),
        installing: 'Installing…',
        installFailed: (message: string) => `Ollama could not be installed: ${message}`,
        startLead: "Ollama is installed but isn't running right now.",
        start: 'Start Ollama',
        starting: 'Starting…',
        startFailed: (message: string) => `Ollama could not be started: ${message}`,
        noModelsTitle: 'Find a model that fits',
        noModelsLead: "Nothing is installed yet. Recommend looks at this computer and suggests models that fit it.",
        goToRecommend: 'Go to Recommend',
        notBenchmarkedTitle: 'See how fast it really runs',
        notBenchmarkedLead:
          "The speeds shown so far are estimates. A quick benchmark replaces one with a real measurement from this computer.",
        goToBenchmarks: 'Go to Benchmarks',
        allGoodTitle: 'Everything is set up',
        allGoodLead: 'See if a model that fits this computer even better has shown up.',
      },
    },
    computer: {
      title: 'Your computer',
      loading: 'Looking at this computer…',
      failed: (message: string) => `This computer could not be read: ${message}`,
      changed:
        "This computer's hardware has changed since the advisor last started. Test results from before stay with the old hardware.",
      factsLabel: 'What this computer has',
      graphics: 'Graphics',
      memory: 'Memory',
      processor: 'Processor',
      modelsSpace: 'Space for models',
      system: 'System',
      noGraphics: 'No graphics card',
      unknown: 'could not be read',
      gpuMemory: (size: string) => `${size} of graphics memory`,
      gpuMemoryUnknown: 'its memory could not be read',
      builtIn: 'built into the processor',
      notUsable: 'Ollama cannot use it',
      unifiedShare: (total: string, usable: string) => `${total}, of which the graphics can use ${usable}`,
      unifiedShareUnknown: (total: string) => `${total}; how much of it the graphics can use could not be read`,
      cores: (physical: number, logical: number) =>
        physical > 0 && logical > physical
          ? `${physical} cores, ${logical} threads`
          : physical > 0
            ? `${physical} cores`
            : logical > 0
              ? `${logical} threads`
              : '',
      freeSpace: (free: string) => `${free} free`,
      folderNotYet: 'Ollama has not created its models folder yet; this is the free space on the drive it will use.',
      showDetails: 'Show details',
      problemsTitle: 'What could not be read',
      filteredTitle: 'Display devices that cannot run models',
      advanced: {
        title: 'Technical details',
        device: 'Device',
        path: 'Runtime path Ollama should use',
        why: 'Why',
        driver: 'Driver',
        memorySource: 'Memory read from',
        ids: 'Identifiers',
        vector: 'Processor extensions',
        vectorValue: (avx2: boolean, avx512: boolean) => `AVX2 ${avx2 ? 'yes' : 'no'}, AVX-512 ${avx512 ? 'yes' : 'no'}`,
        vectorArm: 'ARM processor (AVX does not apply)',
        budget: 'Graphics memory budget',
        modelsFolder: 'Models folder',
        expectations: 'Expectations checked against',
        profile: (id: number, fingerprint: string) => `profile ${id} · ${fingerprint}`,
      },
    },
    ollama: {
      title: 'Ollama',
      placeholder:
        'Whether Ollama is installed and running, one button that says what it will do, and whether it is using your graphics card.',
      step: 'build plan step 3',
    },
    modelDetail: {
      back: 'Back to Recommend',
      loading: 'Reading what is known about this model…',
      failed: (message: string) => `This model could not be read: ${message}`,
      maintainer: (who: string) => `Made by ${who}.`,
      released: (when: string) => ` Released ${when}.`,
      nameInOllama: 'Its name in Ollama',
      machineTitle: 'Your machine — estimated or measured here',
      machineLead: (words: string) => `If Ollama ran it here, keeping about ${words} words in mind:`,
      fit: 'Fit',
      speed: 'Speed',
      noSpeed: 'no estimate yet',
      memory: 'Memory it needs',
      download: 'Download',
      noFile: 'The model list has no file for this size yet, so the advisor cannot say how it would run here.',
      test: 'Test it on this computer',
      testHelp: 'Benchmarks runs a test — downloading the model first if it is not on this computer yet — and a measurement then replaces these estimates.',
      otherFiles: 'Other downloads of this size',
      quant: 'Quantization',
    },
    models: {
      title: 'Models',
      lead: 'Every model Ollama has downloaded on this computer, whether it fits, and how fast it runs.',
      loading: 'Looking at what is installed…',
      failed: (message: string) => `The installed models could not be read: ${message}`,
      backendNotRunning: 'Ollama is not running, so installed models cannot be listed right now.',
      empty: "Nothing is installed yet. Recommend finds models that fit this computer.",
      goToRecommend: 'Go to Recommend',
      name: 'Model',
      fit: 'Fit',
      speed: 'Speed',
      size: 'Size on disk',
      fitUnknown: "The advisor's list does not cover this exact download, so it can't say how well it fits.",
      fitChecking: 'checking…',
      fitCategory: {
        fits_with_headroom: 'Plenty of room',
        fits: 'Fits',
        needs_cpu_offload: 'Runs, partly on the processor',
        reduced_context_only: 'Fits with less room for long documents',
        not_recommended: 'Not a good fit',
        unknown: "Can't tell",
      },
      fitWhy: {
        fits_with_headroom: 'Comfortably within this computer’s memory, with room to spare.',
        fits: 'Within this computer’s memory, without much room to spare.',
        needs_cpu_offload: "Too big to run entirely on the graphics card, so part of it runs on the processor — much slower.",
        reduced_context_only: 'Fits, but only with less room to remember a long conversation or document.',
        not_recommended: "Needs more memory than this computer can give it.",
        unknown: "The advisor's list does not cover this exact download, so it can't say how well it fits.",
      },
      noSpeed: 'not tested',
      details: 'Details',
      freeSpace: (free: string) => `${free} free on the models volume`,
      freeSpaceUnknown: 'The free space on the models volume could not be read.',
      remove: 'Remove',
      removing: 'Removing…',
      removeConfirm: (name: string, gb: string) => `Remove ${name}? This frees ${gb} of disk space. This can't be undone.`,
      removeFailed: (name: string, message: string) => `${name} could not be removed: ${message}`,
      cancel: 'Cancel',
      advanced: {
        family: 'Family',
        parameters: 'Parameters',
        quantization: 'Quantization',
        backend: 'Backend',
        unknown: 'not recorded',
      },
    },
    recommend: {
      title: 'Recommend',
      question: 'What do you want to use AI for?',
      questionHelp: 'Pick one or more. The advisor suggests up to three models that fit this computer.',
      purposes: {
        chat: 'Everyday questions and chat',
        writing: 'Writing and editing text',
        coding: 'Writing and fixing code',
        reasoning: 'Working through hard problems',
        long_context: 'Reading long documents',
        vision: 'Looking at images',
        agentic: 'Multi-step tasks with tools',
      },
      loading: 'Working out what fits this computer…',
      failed: (message: string) => `The advisor could not work out its recommendations: ${message}`,
      pickOne: 'Pick at least one thing above.',
      whyNotUsed: 'Why is my graphics card not used?',
      current: (name: string) => `You have ${name}.`,
      listLabel: 'Recommended models, best first',
      nameInOllama: 'Its name in Ollama',
      speed: 'Speed',
      noSpeed: 'no estimate yet',
      memory: 'Memory it needs',
      download: 'Download',
      installed: 'already on this computer',
      keepsInMind: (words: string) => `Set up to keep about ${words} words in mind at once`,
      details: 'Details: public data and this computer',
      test: 'Test it on this computer',
      why: 'Why this one',
      explainer: 'Why?',
      confidence: {
        high: 'High confidence',
        medium: 'Medium confidence',
        low: 'Low confidence',
      },
      advanced: {
        title: 'Technical details',
        term: 'Term',
        value: 'Value',
        explain: 'What it is',
        weights: { label: 'Weights', explain: 'The model itself, loaded into memory (plus its image reader, when it has one).' },
        kvCache: { label: 'KV cache', explain: 'The memory that holds the conversation so far; it grows with the context.' },
        overhead: { label: 'Runtime overhead', explain: 'What Ollama needs for itself on this kind of graphics.' },
        total: { label: 'Total', explain: 'Everything above, added up.' },
        gpuResident: { label: 'On the graphics', explain: 'The part that lives in graphics memory.' },
        cpuOffload: { label: 'In ordinary memory (offload)', explain: 'The part that lives in the computer\'s ordinary memory instead.' },
        budget: { label: 'Compared against', explain: 'The memory this computer can give a model.' },
        context: { label: 'Context window', explain: 'How many tokens (word pieces) the model keeps in mind at once.' },
        quantization: { label: 'Quantization', explain: 'How much the model\'s numbers were compressed to make the file smaller.' },
        generation: { label: 'Generation', explain: 'Tokens per second while answering; a token is about three quarters of a word.' },
        prompt: { label: 'Prompt processing', explain: 'Tokens per second while reading what you sent.' },
        path: { label: 'Runtime path', explain: 'How Ollama drives this computer\'s graphics — or "cpu" when it does not.' },
        pathExpected: 'expected; not seen yet',
        pathEstablished: 'seen after a load',
        category: { label: 'Fit', explain: 'The comparison that decided whether it fits.' },
        speedBasis: { label: 'Speed estimated from', explain: 'The memory speed of this computer and how much of it models usually achieve.' },
        score: { label: 'Ranking score', explain: 'Purpose × fit × speed × size; only the order matters.' },
        scoreValue: (score: number, p: number, f: number, sp: number, z: number) =>
          `${score} = purpose ${p} × fit ${f} × speed ${sp} × size ${z}`,
        publicAdjust: {
          label: 'Public scores',
          explain: 'How much other people\'s results moved the purpose term (1 = not at all; at most 15% either way). They never touch fit or speed.',
        },
        notes: 'Notes',
        tokens: (n: string) => `${n} tokens`,
      },
    },
    benchmarks: {
      title: 'Benchmarks',
      lead:
        'Test a model on this computer. The advisor sends it passages of its own text, times how fast it reads them and answers, and keeps the result. Nothing you type is ever sent.',
      loading: 'Reading what Ollama has installed, and what else the list has…',
      failed: (message: string) => `The test could not be set up: ${message}`,
      noModels: 'Ollama has no models installed yet, and the list has none that would run here.',
      groupInstalled: 'Models you have installed',
      groupAvailable: "Models you don't have yet (downloaded first)",
      optionInstalled: (name: string, display?: string) => (display ? `${display} (${name})` : name),
      optionAvailable: (display: string, size: string) => `${display} — ${size} download`,
      tooBig: (n: number) =>
        n === 1
          ? 'One more model in the list would not fit this computer, so it is not offered.'
          : `${n} more models in the list would not fit this computer, so they are not offered.`,
      needsDownload: (size: string) => `Not on this computer yet. Testing it downloads it first: ${size}.`,
      fitLabel: 'How it should fit',
      downloadAndRun: (size: string) => `Download ${size}, then run the test`,
      downloading: 'Downloading the model',
      downloadCancel: 'Stop the download',
      downloadStopping: 'Stopping…',
      downloadFailed: (message: string) => `The download did not finish: ${message}`,
      downloadCancelled: 'The download was stopped. Nothing was tested.',
      downloadOther: (name: string) => `Another download is running (${name}); this one can start when it is done.`,
      downloaded: 'Downloaded. Working out the test…',
      startingTest: 'Starting the test: freeing memory, then loading the model — loading can take a minute.',
      model: 'Model',
      context: 'How much text it keeps in mind',
      contextHelp: 'More lets it read longer documents, and needs more memory.',
      contextDefault: (n: string) => `What Ollama uses here (${n} words)`,
      contextOption: (words: string) => `About ${words} words`,
      planning: 'Working out what the test will do…',
      takes: 'Takes',
      takesUnknown: 'a few minutes: there is no speed estimate for this computer yet',
      estimateBefore: 'Estimated before testing',
      lastMeasured: 'Measured here last time',
      promptSkipped: (id: string, why: string) => `The ${id}-token passage is left out: ${why}`,
      promptNote: (id: string, note: string) => `The ${id}-token passage: ${note}`,
      minutes: (lo: number, hi: number) => (hi <= 1 ? 'about a minute' : lo === hi ? `${lo} minutes` : `${lo}–${hi} minutes`),
      run: (lo: number, hi: number) =>
        hi <= 1 ? 'Run a one-minute test' : lo === hi ? `Run a ${lo}-minute test` : `Run a ${lo}–${hi} minute test`,
      runUnknown: 'Run a test (a few minutes)',
      runAnyway: 'Test it anyway (slow)',
      starting: 'Starting…',
      cancel: 'Stop the test and free the memory',
      cancelling: 'Stopping, and freeing the model’s memory…',
      progressLabel: 'Progress',
      step: (step: number, steps: number) => `${step} of ${steps} passages done`,
      timeLeft: 'Time left',
      underAMinute: 'less than a minute',
      result: 'Result',
      answering: 'Answering speed',
      reading: 'Reading speed',
      firstWord: 'Time to the first word',
      memoryTaken: 'Graphics memory it took',
      loadTime: 'Time to load',
      status: {
        queued: 'Waiting',
        running: 'Running',
        done: 'Finished',
        cancelled: 'Stopped',
        failed: 'Did not finish',
      },
      replaced: 'This measurement now replaces the estimate for this model at this setting.',
      notReplaced: 'Kept in the history; the estimate for this setting is unchanged.',
      unloaded: 'The model’s memory was freed afterwards.',
      notUnloaded: 'The model could not be confirmed unloaded afterwards; Ollama may still be holding it.',
      comparison: (diff: string, id: number) => `${diff} against the previous test of the same setting (test ${id}).`,
      notSampled: 'Not measured on this computer',
      notes: 'Worth knowing',
      history: 'Earlier tests',
      historyEmpty: 'No tests yet. The first one takes a few minutes.',
      when: 'When',
      show: 'Show',
      compareSelect: 'Compare',
      compareRowLabel: (model: string, when: string) => `Include ${model} (${when}) in the comparison`,
      comparePick: 'Pick one more test to compare it with.',
      compareButton: 'Compare the two selected tests',
      compareTitle: 'Comparing two tests',
      compareClose: 'Close the comparison',
      compareDiff: (nameA: string, pct: string, nameB: string) => `${nameA} answered ${pct} compared with ${nameB}.`,
      compareRows: {
        metric: 'Metric',
        model: 'Model',
        when: 'When',
        context: 'Context used',
        resident: 'Where it ran',
        residentValue: {
          gpu: 'Graphics card',
          split: 'Graphics card and processor',
          cpu: 'Processor only',
          unknown: 'Not known',
        },
      },
      advanced: {
        title: 'Technical details',
        prompt: { label: 'Passage', explain: 'The length of the text sent, in tokens (word pieces) of this model.' },
        generation: { label: 'Generation', explain: 'Tokens per second while answering; the median of the timed runs.' },
        promptTps: { label: 'Prompt processing', explain: 'Tokens per second while reading the passage.' },
        ttft: { label: 'Time to first token', explain: 'From sending the passage to the first word of the answer, timed by the advisor.' },
        spread: { label: 'Spread', explain: 'How far apart the timed runs were: (fastest − slowest) ÷ median.' },
        config: { label: 'Configuration', explain: 'Everything two tests must share to be compared.' },
        path: { label: 'Runtime path', explain: 'How Ollama drove this computer’s graphics for this test.' },
        kvCache: { label: 'KV cache', explain: 'The memory holding the conversation so far, and the precision it was kept in.' },
        flash: { label: 'Flash attention', explain: 'A faster way of computing attention that Ollama turns on where the graphics support it.' },
        context: { label: 'Context window', explain: 'How many tokens the model kept in mind during the test.' },
        quantization: { label: 'Quantization', explain: 'How much the model’s numbers were compressed to make the file smaller.' },
        suite: { label: 'Test suite', explain: 'The version of the advisor’s own passages and settings; tests of different versions are not compared.' },
        resources: { label: 'Resources', explain: 'What the graphics and the computer did while the passages were timed.' },
        yes: 'on',
        no: 'off',
        unknown: 'not known',
      },
    },
    watch: {
      title: 'New models',
      placeholder:
        'What the advisor checked for you, when, what it found, and why it did or did not tell you.',
      step: 'build plan step 10',
    },
    settings: {
      title: 'Settings',
      advancedLabel: 'Show advanced details',
      advancedHelp:
        'Off by default. When on, screens also show the technical columns — memory arithmetic, quantization names, tokens per second breakdowns.',
      notificationsTitle: 'Notifications',
      notificationsStep: 'build plan step 10',
      updatesTitle: 'Updates',
      updatesStep: 'build plan step 11',
      version: (v: string) => `version ${v}`,
      versionPlatform: (os: string, arch: string) => `${os}/${arch}`,
      modelsFolder: 'Models folder',
      modelsFolderUnknown: 'could not be read yet',
      dataFolder: 'Data folder',
      open: 'Open',
      opening: 'Opening…',
      openFailed: (message: string) => `That folder could not be opened: ${message}`,
      freeSpace: (free: string) => `${free} free`,
      freeSpaceUnknown: 'could not be read',
    },
  },
  onboarding: {
    gateLoading: 'Checking whether setup has run before…',
    progress: 'Setup progress',
    welcome: {
      title: 'Welcome',
      what: 'This app looks at your computer, then tells you which AI models it can run well — and how well, with an honest number once it has actually tried one.',
      notChat: "It doesn't chat with you itself; it finds, downloads and tests models for the chat apps that do.",
      start: "Let's look at your computer",
    },
    checking: {
      title: 'Checking your computer',
      loading: 'Looking at this computer…',
      failed: (message: string) => `This computer could not be read: ${message}`,
      showDetails: 'Show details',
      graphics: 'Graphics',
      noGraphics: 'No graphics card',
      memory: 'Memory',
      unknown: 'could not be read',
      processor: 'Processor',
      continue: 'Continue',
    },
    tier: {
      unknown: 'Not enough could be read to place this computer',
      cpu_only: 'No graphics card the advisor can use — small models only, at a modest speed',
      integrated: 'Graphics built into the processor — small and medium models',
      gpu_small: 'A small graphics card',
      gpu_medium: 'A medium graphics card',
      gpu_large: 'A large graphics card',
      gpu_xl: 'A very large graphics card',
    },
    ollama: {
      title: 'Ollama',
      lead:
        "Ollama is the free program that runs AI models on this computer, using the graphics card's own memory (",
      leadTermVram: 'VRAM',
      leadSuffix: ') when there is one. The advisor uses it to download and run whatever you pick next.',
      loading: 'Looking for Ollama…',
      failed: (message: string) => `Ollama could not be checked: ${message}`,
      found: (version: string) => (version ? `Found Ollama ${version}.` : 'Found Ollama.'),
      installedModelsLabel: 'Already installed',
      continue: 'Continue',
      install: (size?: string) => (size ? `Install Ollama (about ${size})` : 'Install Ollama'),
      installing: 'Installing Ollama…',
      installFailed: (message: string) => `The install did not finish: ${message}`,
      start: 'Start Ollama',
      starting: 'Starting…',
      startFailed: (message: string) => `Ollama did not start: ${message}`,
      unsupported: "Ollama has no build for this computer's operating system.",
    },
    purposes: {
      title: 'What will you use AI for?',
      help: 'Pick as many as apply. The advisor suggests up to three models that fit this computer.',
      continue: 'Continue',
      labels: {
        chat: 'Not sure — general chat',
        writing: 'Writing and editing text',
        coding: 'Writing and fixing code',
        reasoning: 'Working through hard problems',
        long_context: 'Reading long documents',
        vision: 'Looking at images',
        agentic: 'Multi-step tasks with tools',
      },
    },
    recommend: {
      title: 'Recommendations',
      loading: 'Working out what fits this computer…',
      failed: (message: string) => `The advisor could not work out its recommendations: ${message}`,
      empty: 'Nothing in the catalogue fits this computer yet.',
      listLabel: 'Recommended models, best first',
      speed: 'Speed',
      noSpeed: 'no estimate yet',
      download: 'Download',
      installed: 'already on this computer',
      keepsInMind: (words: string) => `Keeps about ${words} words of `,
      keepsInMindSuffix: ' in mind at once.',
      downloadButton: (size: string) => `Download ${size}`,
      continueInstalled: 'Already installed — continue',
    },
    getting: {
      title: 'Getting it',
      lead: (name: string) => `Getting ${name} ready.`,
      fileNotePrefix: 'Ollama downloads the model as one file, a',
      fileNoteSuffix: 'from its own library.',
      failed: (message: string) => `The download could not be started: ${message}`,
      downloading: 'Downloading…',
      cancel: 'Stop the download',
      cancelling: 'Stopping…',
      pullFailed: (message: string) => `The download did not finish: ${message}`,
      cancelled: 'Stopped. Go back and pick a model to try again.',
    },
    tryit: {
      title: 'Try it',
      lead: 'One quick test: the advisor sends this model a short passage of its own text and times how many ',
      leadTermTokens: 'tok/s',
      leadSuffix: " it answers with. Nothing you type is ever sent — this is the advisor's own text, and it takes about a minute.",
      failed: (message: string) => `The test could not be started: ${message}`,
      run: 'Run a one-minute test',
      starting: 'Starting…',
      estimated: 'Estimated before testing',
      measured: 'Measured on this computer',
      continue: 'Continue',
      testFailed: (message: string) => `The test did not finish: ${message}`,
      noSpeed: 'The test finished, but too little was answered to time it.',
    },
    useit: {
      title: 'Use it',
      lead: "Setup is done. Here's the exact name to give it in a chat app:",
      copy: 'Copy',
      copied: 'Copied',
      checkingApps: 'Looking for chat apps on this computer…',
      foundLead: 'Found on this computer:',
      noneFoundLead: 'No chat app was found on this computer yet. Any of these can talk to the model above:',
      finish: 'Finish setup',
      finishing: 'Finishing…',
    },
  },
  placeholder: {
    comingIn: (step: string) => `This screen is filled in by ${step}.`,
  },
} as const
