// Every string the UI shows, in one place, from day one (i18n-ready,
// English only). Screens import from here; they do not carry prose of
// their own. Step 7 adds the glossary (one-line explainers for every
// technical term) next to this file.

export const en = {
  app: {
    title: 'Local LLM Advisor',
    tagline: 'Which AI models fit this computer, and how well they run.',
    advancedOn: 'Advanced',
    version: (v: string) => `version ${v}`,
    daemonUnreachable: 'The advisor is not running on this computer. Start it and reload this page.',
  },
  figure: {
    estimatedLabel: 'estimated',
    measuredLabel: 'measured on this computer',
    estimatedPrefix: '≈',
  },
  nav: {
    home: 'Home',
    computer: 'Your computer',
    ollama: 'Ollama',
    models: 'Models',
    recommend: 'Recommend',
    benchmarks: 'Benchmarks',
    watch: 'New models',
    settings: 'Settings',
  },
  screens: {
    home: {
      title: 'Home',
      placeholder:
        'Your computer in one sentence, the model you use today, and the single most useful thing to do next.',
      step: 'build plan step 8',
    },
    computer: {
      title: 'Your computer',
      loading: 'Looking at this computer…',
      failed: (message: string) => `This computer could not be read: ${message}`,
      changed:
        "This computer's hardware has changed since the advisor last started. Test results from before stay with the old hardware.",
      factsLabel: 'What this computer has',
      graphics: 'Graphics',
      memory: 'Memory',
      processor: 'Processor',
      modelsSpace: 'Space for models',
      system: 'System',
      noGraphics: 'No graphics card',
      unknown: 'could not be read',
      gpuMemory: (size: string) => `${size} of graphics memory`,
      gpuMemoryUnknown: 'its memory could not be read',
      builtIn: 'built into the processor',
      notUsable: 'Ollama cannot use it',
      unifiedShare: (total: string, usable: string) => `${total}, of which the graphics can use ${usable}`,
      unifiedShareUnknown: (total: string) => `${total}; how much of it the graphics can use could not be read`,
      cores: (physical: number, logical: number) =>
        physical > 0 && logical > physical
          ? `${physical} cores, ${logical} threads`
          : physical > 0
            ? `${physical} cores`
            : logical > 0
              ? `${logical} threads`
              : '',
      freeSpace: (free: string) => `${free} free`,
      folderNotYet: 'Ollama has not created its models folder yet; this is the free space on the drive it will use.',
      showDetails: 'Show details',
      problemsTitle: 'What could not be read',
      filteredTitle: 'Display devices that cannot run models',
      advanced: {
        title: 'Technical details',
        device: 'Device',
        path: 'Runtime path Ollama should use',
        why: 'Why',
        driver: 'Driver',
        memorySource: 'Memory read from',
        ids: 'Identifiers',
        vector: 'Processor extensions',
        vectorValue: (avx2: boolean, avx512: boolean) => `AVX2 ${avx2 ? 'yes' : 'no'}, AVX-512 ${avx512 ? 'yes' : 'no'}`,
        vectorArm: 'ARM processor (AVX does not apply)',
        budget: 'Graphics memory budget',
        modelsFolder: 'Models folder',
        expectations: 'Expectations checked against',
        profile: (id: number, fingerprint: string) => `profile ${id} · ${fingerprint}`,
      },
    },
    ollama: {
      title: 'Ollama',
      placeholder:
        'Whether Ollama is installed and running, one button that says what it will do, and whether it is using your graphics card.',
      step: 'build plan step 3',
    },
    models: {
      title: 'Models',
      placeholder:
        'The models installed on this computer, whether each one fits, and how fast it runs — estimated until measured.',
      step: 'build plan steps 3, 4 and 8',
    },
    recommend: {
      title: 'Recommend',
      question: 'What do you want to use AI for?',
      questionHelp: 'Pick one or more. The advisor suggests up to three models that fit this computer.',
      purposes: {
        chat: 'Everyday questions and chat',
        writing: 'Writing and editing text',
        coding: 'Writing and fixing code',
        reasoning: 'Working through hard problems',
        long_context: 'Reading long documents',
        vision: 'Looking at images',
        agentic: 'Multi-step tasks with tools',
      },
      loading: 'Working out what fits this computer…',
      failed: (message: string) => `The advisor could not work out its recommendations: ${message}`,
      pickOne: 'Pick at least one thing above.',
      fetchList: 'Fetch the model list (about 10 MB)',
      fetching: 'Fetching the model list from Hugging Face… this takes a minute or two.',
      fetchFailed: (message: string) => `The model list could not be fetched: ${message}`,
      whyNotUsed: 'Why is my graphics card not used?',
      current: (name: string) => `You have ${name}.`,
      listLabel: 'Recommended models, best first',
      nameInOllama: 'Its name in Ollama',
      speed: 'Speed',
      noSpeed: 'no estimate yet',
      memory: 'Memory it needs',
      download: 'Download',
      installed: 'already on this computer',
      keepsInMind: (words: string) => `Set up to keep about ${words} words in mind at once`,
      why: 'Why this one',
      explainer: 'Why?',
      confidence: {
        high: 'High confidence',
        medium: 'Medium confidence',
        low: 'Low confidence',
      },
      advanced: {
        title: 'Technical details',
        term: 'Term',
        value: 'Value',
        explain: 'What it is',
        weights: { label: 'Weights', explain: 'The model itself, loaded into memory (plus its image reader, when it has one).' },
        kvCache: { label: 'KV cache', explain: 'The memory that holds the conversation so far; it grows with the context.' },
        overhead: { label: 'Runtime overhead', explain: 'What Ollama needs for itself on this kind of graphics.' },
        total: { label: 'Total', explain: 'Everything above, added up.' },
        gpuResident: { label: 'On the graphics', explain: 'The part that lives in graphics memory.' },
        cpuOffload: { label: 'In ordinary memory (offload)', explain: 'The part that lives in the computer\'s ordinary memory instead.' },
        budget: { label: 'Compared against', explain: 'The memory this computer can give a model.' },
        context: { label: 'Context window', explain: 'How many tokens (word pieces) the model keeps in mind at once.' },
        quantization: { label: 'Quantization', explain: 'How much the model\'s numbers were compressed to make the file smaller.' },
        generation: { label: 'Generation', explain: 'Tokens per second while answering; a token is about three quarters of a word.' },
        prompt: { label: 'Prompt processing', explain: 'Tokens per second while reading what you sent.' },
        path: { label: 'Runtime path', explain: 'How Ollama drives this computer\'s graphics — or "cpu" when it does not.' },
        pathExpected: 'expected; not seen yet',
        pathEstablished: 'seen after a load',
        category: { label: 'Fit', explain: 'The comparison that decided whether it fits.' },
        speedBasis: { label: 'Speed estimated from', explain: 'The memory speed of this computer and how much of it models usually achieve.' },
        score: { label: 'Ranking score', explain: 'Purpose × fit × speed × size; only the order matters.' },
        scoreValue: (score: number, p: number, f: number, sp: number, z: number) =>
          `${score} = purpose ${p} × fit ${f} × speed ${sp} × size ${z}`,
        notes: 'Notes',
        tokens: (n: string) => `${n} tokens`,
      },
    },
    benchmarks: {
      title: 'Benchmarks',
      lead:
        'Test a model on this computer. The advisor sends it passages of its own text, times how fast it reads them and answers, and keeps the result. Nothing you type is ever sent.',
      loading: 'Reading what Ollama has installed…',
      failed: (message: string) => `The test could not be set up: ${message}`,
      noModels: 'Ollama has no models installed yet. Download one first, then test it here.',
      model: 'Model',
      context: 'How much text it keeps in mind',
      contextHelp: 'More lets it read longer documents, and needs more memory.',
      contextDefault: (n: string) => `What Ollama uses here (${n} words)`,
      contextOption: (words: string) => `About ${words} words`,
      planning: 'Working out what the test will do…',
      takes: 'Takes',
      takesUnknown: 'a few minutes: there is no speed estimate for this computer yet',
      estimateBefore: 'Estimated before testing',
      lastMeasured: 'Measured here last time',
      promptSkipped: (id: string, why: string) => `The ${id}-token passage is left out: ${why}`,
      promptNote: (id: string, note: string) => `The ${id}-token passage: ${note}`,
      minutes: (lo: number, hi: number) => (hi <= 1 ? 'about a minute' : lo === hi ? `${lo} minutes` : `${lo}–${hi} minutes`),
      run: (lo: number, hi: number) =>
        hi <= 1 ? 'Run a one-minute test' : lo === hi ? `Run a ${lo}-minute test` : `Run a ${lo}–${hi} minute test`,
      runUnknown: 'Run a test (a few minutes)',
      runAnyway: 'Test it anyway (slow)',
      starting: 'Starting…',
      cancel: 'Stop the test and free the memory',
      cancelling: 'Stopping, and freeing the model’s memory…',
      progressLabel: 'Progress',
      step: (step: number, steps: number) => `${step} of ${steps} passages done`,
      timeLeft: 'Time left',
      underAMinute: 'less than a minute',
      result: 'Result',
      answering: 'Answering speed',
      reading: 'Reading speed',
      firstWord: 'Time to the first word',
      memoryTaken: 'Graphics memory it took',
      loadTime: 'Time to load',
      status: {
        queued: 'Waiting',
        running: 'Running',
        done: 'Finished',
        cancelled: 'Stopped',
        failed: 'Did not finish',
      },
      replaced: 'This measurement now replaces the estimate for this model at this setting.',
      notReplaced: 'Kept in the history; the estimate for this setting is unchanged.',
      unloaded: 'The model’s memory was freed afterwards.',
      notUnloaded: 'The model could not be confirmed unloaded afterwards; Ollama may still be holding it.',
      comparison: (diff: string, id: number) => `${diff} against the previous test of the same setting (test ${id}).`,
      notSampled: 'Not measured on this computer',
      notes: 'Worth knowing',
      history: 'Earlier tests',
      historyEmpty: 'No tests yet. The first one takes a few minutes.',
      when: 'When',
      show: 'Show',
      advanced: {
        title: 'Technical details',
        prompt: { label: 'Passage', explain: 'The length of the text sent, in tokens (word pieces) of this model.' },
        generation: { label: 'Generation', explain: 'Tokens per second while answering; the median of the timed runs.' },
        promptTps: { label: 'Prompt processing', explain: 'Tokens per second while reading the passage.' },
        ttft: { label: 'Time to first token', explain: 'From sending the passage to the first word of the answer, timed by the advisor.' },
        spread: { label: 'Spread', explain: 'How far apart the timed runs were: (fastest − slowest) ÷ median.' },
        config: { label: 'Configuration', explain: 'Everything two tests must share to be compared.' },
        path: { label: 'Runtime path', explain: 'How Ollama drove this computer’s graphics for this test.' },
        kvCache: { label: 'KV cache', explain: 'The memory holding the conversation so far, and the precision it was kept in.' },
        flash: { label: 'Flash attention', explain: 'A faster way of computing attention that Ollama turns on where the graphics support it.' },
        context: { label: 'Context window', explain: 'How many tokens the model kept in mind during the test.' },
        quantization: { label: 'Quantization', explain: 'How much the model’s numbers were compressed to make the file smaller.' },
        suite: { label: 'Test suite', explain: 'The version of the advisor’s own passages and settings; tests of different versions are not compared.' },
        resources: { label: 'Resources', explain: 'What the graphics and the computer did while the passages were timed.' },
        yes: 'on',
        no: 'off',
        unknown: 'not known',
      },
    },
    watch: {
      title: 'New models',
      placeholder:
        'What the advisor checked for you, when, what it found, and why it did or did not tell you.',
      step: 'build plan step 10',
    },
    settings: {
      title: 'Settings',
      placeholder:
        'Notifications, where models and data are kept, the version, and checking for updates.',
      step: 'build plan step 8',
      advancedLabel: 'Show advanced details',
      advancedHelp:
        'Off by default. When on, screens also show the technical columns — memory arithmetic, quantization names, tokens per second breakdowns.',
    },
  },
  placeholder: {
    comingIn: (step: string) => `This screen is filled in by ${step}.`,
  },
} as const
